
/*
	
TRIGGER QUE ACTUALIZA LA PUNTUACIÓN DEL SOCIO QUE REALIZA UNA OPERACIÓN.
SE SUMA O SE RESTA SEGÚN EL TIPO DE PUNTUACIÓN QUE SEA Y SI EL DÉFICIT ES MENOR QUE -30
AL FINALIZAR LA OPERACIÓN, NO SE REALIZA.
*/
DELIMITER |

CREATE TRIGGER ACTUALIZAR_PUNTUACION AFTER INSERT ON HISTORICO_PUNTUACIONES
FOR EACH ROW
BEGIN

DECLARE PUNTUACIONTIPO INT;
DECLARE PUNTUACIONSOCIO INT;
SET PUNTUACIONTIPO=(SELECT VALOR FROM TIPOS_PUNTUACION WHERE ID_TIPO_PUNTUACION=NEW.TIPO_PUNTUACION);
SET PUNTUACIONSOCIO=(SELECT PUNTUACION FROM SOCIOS WHERE ID_SOCIO=NEW.SOCIO);


IF (PUNTUACIONSOCIO+PUNTUACIONTIPO)>=(SELECT VALOR FROM TIPOS_PUNTUACION WHERE TIPO='DEFICIT') THEN
	UPDATE SOCIOS
	SET PUNTUACION = PUNTUACION+PUNTUACIONTIPO
	WHERE ID_SOCIO=NEW.SOCIO;

ELSE
	DELETE FROM HISTORICO_PUNTUACIONES
    WHERE ID_PUNTUACION=NEW.ID_PUNTUACION;
	
END IF;
END
|
DELIMITER ;

-- INSERT INTO HISTORICO_PUNTUACIONES (FECHA,TIPO_PUNTUACION,SOCIO) VALUES(NOW(),5,3);



/*
TRIGGER QUE ACTUALIZA EL HISTÓRICO DE PUNTUACIONES AL DAR DE ALTA UNA MOVILIDAD EN UNA EMPRESA


*/
DELIMITER |

CREATE TRIGGER ACTUALIZAR_HISTORICO_PUNTUACIONES_MOVILIDAD_EMPRESA AFTER INSERT ON MOVILIDADES_EMPRESAS
FOR EACH ROW
BEGIN


 INSERT INTO HISTORICO_PUNTUACIONES (FECHA,TIPO_PUNTUACION,SOCIO) VALUES(NOW(),(SELECT ID_TIPO_PUNTUACION FROM TIPOS_PUNTUACION WHERE TIPO='MOBILITY'),(SELECT SOCIO FROM ALUMNOS WHERE ID_ALUMNO=NEW.ALUMNO));

END
|
DELIMITER ;

/*
TRIGGER QUE ACTUALIZA EL HISTÓRICO DE PUNTUACIONES AL DAR DE ALTA UNA MOVILIDAD EN UNA INSTITUCIÓN

*/

DELIMITER |

CREATE TRIGGER ACTUALIZAR_HISTORICO_PUNTUACIONES_MOVILIDAD_INSTITUCION AFTER INSERT ON MOVILIDADES_INSTITUCIONES
FOR EACH ROW
BEGIN

INSERT INTO HISTORICO_PUNTUACIONES (FECHA,TIPO_PUNTUACION,SOCIO) VALUES(NOW(),(SELECT ID_TIPO_PUNTUACION FROM TIPOS_PUNTUACION WHERE TIPO='MOBILITY'),(SELECT SOCIO FROM ALUMNOS WHERE ID_ALUMNO=NEW.ALUMNO));

END
|
DELIMITER ;


DROP TRIGGER ACTUALIZAR_HISTORICO_PUNTUACIONES_ALTA_EMPRESA;

DELIMITER |

CREATE TRIGGER ACTUALIZAR_HISTORICO_PUNTUACIONES_ALTA_EMPRESA AFTER INSERT ON EMPRESAS
FOR EACH ROW
BEGIN

INSERT INTO HISTORICO_PUNTUACIONES (FECHA,TIPO_PUNTUACION,SOCIO) VALUES (NOW(),(SELECT ID_TIPO_PUNTUACION FROM TIPOS_PUNTUACION WHERE TIPO='COMPANY REGISTER'),(SELECT SOCIO FROM EMPRESAS WHERE ID_EMPRESA=NEW.ID_EMPRESA));

END


| DELIMITER ;



DELIMITER |



| DELIMITER ;


