

DELIMITER |

CREATE TRIGGER SUMARPUNTUACION AFTER INSERT ON HISTORICO_PUNTUACIONES
FOR EACH ROW
BEGIN

UPDATE SOCIOS
SET PUNTUACION = PUNTUACION+(SELECT VALOR FROM TIPOS_PUNTUACION WHERE ID_TIPO_PUNTUACION=NEW.TIPO_PUNTUACION)
WHERE ID_SOCIO=NEW.SOCIO;

END
|
DELIMITER ;