CREATE USER IF NOT EXISTS 'login'@'localhost' IDENTIFIED WITH mysql_native_password USING PASSWORD('abc123.');
CREATE USER IF NOT EXISTS 'dbadministrator'@'localhost' IDENTIFIED WITH mysql_native_password USING PASSWORD('abc123.');
CREATE USER IF NOT EXISTS 'registered'@'localhost' IDENTIFIED WITH mysql_native_password USING PASSWORD('abc123.');
GRANT SELECT ON GESTIONMOVILIDADES.SOCIOS TO 'login'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.ROL_USUARIOS TO 'login'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.EMPRESAS TO 'login'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.TIPOS_EMPRESA TO 'login'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.PAISES TO 'login'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.TIPOS_INSTITUCION TO 'login'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.INSTITUCIONES TO 'login'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.SOCIOS TO 'login'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.INSTITUCIONES TO 'login'@'localhost';
GRANT UPDATE (INSTITUCION) ON GESTIONMOVILIDADES.SOCIOS TO 'login'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.TIPOS_EMPRESA TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.RESPONSABLES TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.EMPRESAS TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.PAISES TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.SOCIOS TO 'registered'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.EMPRESAS TO 'registered'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.ALUMNOS TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.ALUMNOS TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.TIPOS_ESPECIALIDAD TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.ALUMNOS_ESPECIALIDADES TO 'registered'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.MOVILIDADES_EMPRESAS TO 'registered'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.MOVILIDADES_INSTITUCIONES TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.INSTITUCIONES TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.MOVILIDADES_EMPRESAS TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.MOVILIDADES_INSTITUCIONES TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.HISTORICO_PUNTUACIONES TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.TIPOS_PUNTUACION TO 'registered'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.TIPOS_ESPECIALIDAD TO 'dbadministrator'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.TIPOS_INSTITUCION TO 'dbadministrator'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.TIPOS_EMPRESA TO 'dbadministrator'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.TIPOS_PUNTUACION TO 'login'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.ALUMNOS_ESPECIALIDADES TO 'registered'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.EMPRESAS_ESPECIALIDADES TO 'registered'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.INSTITUCIONES_ESPECIALIDADES TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.MOVILIDADES_EMPRESAS TO 'dbadministrator'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.MOVILIDADES_INSTITUCIONES TO 'dbadministrator'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.EMPRESAS TO 'dbadministrator'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.PAISES TO 'dbadministrator'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.ALUMNOS TO 'dbadministrator'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.INSTITUCIONES TO 'dbadministrator'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.RESPONSABLES TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.HISTORICO_PETICIONES TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.ESTADOS TO 'registered'@'localhost';
GRANT INSERT ON GESTIONMOVILIDADES.HISTORICO_PETICIONES TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.ROL_USUARIOS TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.SOCIOS TO 'dbadministrator'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.HISTORICO_PETICIONES TO 'dbadministrator'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.ESTADOS TO 'dbadministrator'@'localhost';
GRANT UPDATE ON GESTIONMOVILIDADES.RESPONSABLES TO 'registered'@'localhost';
GRANT UPDATE ON GESTIONMOVILIDADES.EMPRESAS TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.TIPOS_ESPECIALIDAD TO 'dbadministrator'@'localhost';
GRANT UPDATE ON GESTIONMOVILIDADES.SOCIOS TO 'registered'@'localhost';
GRANT SELECT ON GESTIONMOVILIDADES.TIPOS_EMPRESA TO 'dbadministrator'@'localhost';
GRANT UPDATE ON GESTIONMOVILIDADES.HISTORICO_PETICIONES TO 'dbadministrator'@'localhost';













